- web/components/Account/Message/Conversation.tsx
- web/hooks/useBookings.ts
> Add conversation id in useBookings

- back/api/booking/documentation/1.0.0/booking.json
- back/api/disponibility/controllers/disponibility.js
- back/api/disponibility/documentation/1.0.0/disponibility.json
- back/api/dispositif/documentation/1.0.0/dispositif.json
- back/api/dispositif/models/dispositif.settings.json
- back/api/espace/controllers/espace.js
- back/api/espace/documentation/1.0.0/espace.json
- back/api/espace/services/espace.js
- back/api/message/documentation/1.0.0/message.json
- back/extensions/documentation/documentation/1.0.0/full_documentation.json
- back/extensions/users-permissions/documentation/1.0.0/overrides/users-permissions-User.json
- back/extensions/users-permissions/documentation/1.0.0/users-permissions-Role.json
- back/extensions/users-permissions/documentation/1.0.0/users-permissions-User.json
- back/extensions/users-permissions/models/User.settings.json
- web/components/Account/Place/ScheduleDispositif.tsx
- web/typings/api.ts
Permet d'allouer des créneaux horaires à des compagnies spécifiques
> Màj dispositif

- web/pages/espaces/index.tsx
Fix page espaces sans campagne
> Fix espace page when no applications

- back/api/application/documentation/1.0.0/application.json
- back/api/booking/documentation/1.0.0/booking.json
- back/api/campaign/documentation/1.0.0/campaign.json
- back/api/campaign/models/campaign.settings.json
- back/api/disponibility/documentation/1.0.0/disponibility.json
- back/api/dispositif/documentation/1.0.0/dispositif.json
- back/api/espace/documentation/1.0.0/espace.json
- back/api/message/documentation/1.0.0/message.json
- back/extensions/documentation/documentation/1.0.0/full_documentation.json
- back/extensions/users-permissions/documentation/1.0.0/users-permissions-Role.json
- back/extensions/users-permissions/documentation/1.0.0/users-permissions-User.json
- back/extensions/users-permissions/models/User.settings.json
- web/components/Account/Place/PlaceTabList.tsx
- web/components/Campaign/CampaignContext.tsx
- web/components/Campaign/CampaignProvider.tsx
- web/components/Campaign/Home/HomeCampaignInsert.tsx
- web/components/Home/HomeActions.tsx
- web/components/Home/HomeCarousel.tsx
- web/pages/compte/espaces/index.tsx
- web/typings/api.ts
**Issue**
https://github.com/premieroctet/studio-d-suivi/issues/25
- home design fix
- max candidatures dans modèle campagne
- relation user pour limiter les lieux dans le modèle campagne
- limitation mode campagne lieu en front si lieu non lié à campagne
> Campaign place relation + home improvement

- back/api/campaign/documentation/1.0.0/campaign.json
- back/api/disponibility/documentation/1.0.0/disponibility.json
- back/extensions/documentation/documentation/1.0.0/full_documentation.json
- back/extensions/users-permissions/documentation/1.0.0/users-permissions-User.json
- web/components/Account/Place/PlaceTabList.tsx
- fix calcul du nombre de créneaux campagne
- modif modèle campagne
> Campaign slots number

- back/extensions/documentation/documentation/1.0.0/full_documentation.json
- web/components/Campaign/Places/PlacesListCampaignHelper.tsx
- web/components/Home/HomePlaces.tsx
- web/components/Place/PlaceGridCard.tsx
**Issue**
https://github.com/premieroctet/studio-d-suivi/issues/17
> Line and style fixes

- back/extensions/documentation/documentation/1.0.0/full_documentation.json
- web/components/Account/Place/ListItem/PlaceListItem.tsx
- web/components/Account/Place/ListItem/SubInfo.tsx
- web/components/Account/Place/PlaceList.tsx
- web/components/Account/Place/PlaceTabList.tsx
- web/components/Account/Place/Schedule.tsx
- web/components/Account/Place/ScheduleForm.tsx
- web/components/Campaign/Places/CampaignDatePicker.tsx
- web/components/Campaign/Places/CampaignSchedule.tsx
- web/components/Campaign/Places/CampaignScheduleForm.tsx
- web/components/Campaign/Places/CampaignScheduleInfo.tsx
- web/components/Campaign/Places/PlacesListCampaignHelper.tsx
- web/components/Home/HomePlaces.tsx
- web/components/InputMultiSelect.tsx
- web/components/Place/PlaceGridCard.tsx
- web/hooks/useNbDisponibility.tsx
**Issue**
https://github.com/premieroctet/studio-d-suivi/issues/2
> Fix campaign slot creation form

- web/components/Account/Place/DeletePlaceModal.tsx
- web/components/Account/Place/ListItem/CampaignDisponibilitiesInfo.tsx
- web/components/Account/Place/ListItem/NoContent.tsx
- web/components/Account/Place/ListItem/PlaceActions.tsx
- web/components/Account/Place/ListItem/PlaceDisponibilitiesInfo.tsx
- web/components/Account/Place/ListItem/PlaceListItem.tsx
- web/components/Account/Place/ListItem/PlaceListItemImage.tsx
- web/components/Account/Place/ListItem/PlaceListItemInfo.tsx
- web/components/Account/Place/PublishModal.tsx
- web/components/Account/Place/UnpublishModal.tsx
- web/public/assets/icons/EyeIcon.tsx
- web/public/assets/img/eye.svg
- web/public/locales/fr/place.json
- web/theme/components/Button.ts
**Issue**
https://github.com/premieroctet/studio-d-suivi/issues/26
> Spaces listing in admin

- back/extensions/documentation/documentation/1.0.0/full_documentation.json
- web/components/Account/AccountMenu.tsx
- web/components/Campaign/CampaignTag.tsx
- web/components/Campaign/Places/Application/CampaignApplicationSchedule.tsx
- web/components/Campaign/Places/Application/CampaignApplicationScheduleItem.tsx
- web/components/Campaign/Places/Application/Inputs/CheckboxField.tsx
- web/components/Campaign/Places/Application/LockedApplications.tsx
- web/components/Place/PlaceGridCard.tsx
- web/components/Place/PlaceListCard.tsx
- web/components/Place/PlacesTab.tsx
- web/components/Tag.tsx
- web/hooks/useCurrentUser.tsx
- web/public/locales/fr/common.json
- web/public/locales/fr/place.json
- Tag candidature déposée sur les listing de lieux
- Compteur candidatures dans le useCurrent user
- Blocage des candidatures sur les dispos déjà candidatées
- Message si candidature bloquée
> Lock applications

- web/components/Campaign/Places/PlacesListCampaignHelper.tsx
- web/components/Home/HomePlaces.tsx
- web/public/locales/fr/home.json
> Fix style on home

- web/@types/reference.d.ts
- web/components/Campaign/Places/Application/ApplicationForm.tsx
- web/components/Campaign/Places/Application/ApplicationGeneral.tsx
- web/components/Campaign/Places/Application/CampaignApplicationPopin.tsx
- web/components/Campaign/Places/Application/Inputs/BooleanField.tsx
- web/components/Campaign/Places/Application/Inputs/TextAreaField.tsx
- web/components/Campaign/Places/Application/References/ReferenceItem.tsx
- web/components/Campaign/Places/PlacesListCampaignHelper.tsx
- web/components/Home/HomePlaces.tsx
- web/components/InputMultiSelect.tsx
- web/hooks/useCurrentUser.tsx
- ajout des infos de la dernière candidature dans le formulaire de candidature
> Add info into application form

- back/api/application/controllers/application.js
- back/api/application/documentation/1.0.0/application.json
- back/api/application/models/application.settings.json
- back/api/booking/documentation/1.0.0/booking.json
- back/api/campaign/documentation/1.0.0/campaign.json
- back/api/city/documentation/1.0.0/city.json
- back/api/disponibility/documentation/1.0.0/disponibility.json
- back/api/espace/documentation/1.0.0/espace.json
- back/api/espace/models/espace.settings.json
- back/extensions/documentation/documentation/1.0.0/full_documentation.json
- back/extensions/users-permissions/documentation/1.0.0/users-permissions-User.json
- web/components/Account/Application/Company/ApplicationCompanyList.tsx
- web/components/Account/Application/Company/ApplicationCompanyListItem.tsx
- web/components/Account/Application/Place/ApplicationPlaceList.tsx
- web/components/Account/Application/Place/ApplicationPlaceListItem.tsx
- web/components/Account/Application/Place/ApplicationSelector.tsx
- web/components/Campaign/CampaignTag.tsx
- web/components/Campaign/Places/Application/ApplicationForm.tsx
- web/components/Place/PlaceGridCard.tsx
- web/pages/compte/candidatures/index.tsx
- web/public/locales/fr/account.json
- web/public/locales/fr/application.json
- Listing des candidatures pour les lieux
> Basis for applications place listing

- web/components/Account/Application/Place/Selectors/ApplicationSelector.tsx
- web/components/Campaign/Places/Admin/CampaignScheduleInfo.tsx
- Lien entre le planning et les candidatures
> Link applications to space schedule

- web/pages/[id].tsx
> Add dynamic pages

- back/extensions/documentation/documentation/1.0.0/full_documentation.json
- web/components/Account/Place/ListItem/CampaignDisponibilitiesInfo.tsx
- web/components/Account/Place/ListItem/PlaceListItem.tsx
- web/components/Account/Place/PlaceTabList.tsx
- web/components/Campaign/CampaignTag.tsx
- web/components/Campaign/Places/Admin/CampaignScheduleInfo.tsx
- web/components/Campaign/Places/Detail/CampaignPlaceDetail.tsx
- web/components/Place/PlaceGridCard.tsx
- web/components/Place/PlaceListCard.tsx
- web/hooks/useCampaignDispo.tsx
- web/hooks/useCurrentUser.tsx
- web/hooks/useSelectedCampaign.tsx
- web/pages/compte/candidatures/index.tsx
> Fix dispo check

- back/api/application/controllers/application.js
- back/extensions/documentation/documentation/1.0.0/full_documentation.json
- web/components/Account/Application/Place/ApplicationPlaceList.tsx
- web/components/Account/Application/Place/ApplicationPlaceListItem.tsx
- web/components/Account/Application/Place/DetailDrawer/ApplicationDetailDrawer.tsx
- web/components/Account/Application/Place/DetailDrawer/ApplicationDetailHeader.tsx
- web/components/Account/Application/Place/DetailDrawer/ApplicationDetailInfos.tsx
- web/components/Account/Application/Place/DetailDrawer/ApplicationPdf.tsx
- web/components/Account/Application/Place/DetailDrawer/ApplicationRightPanel.tsx
- web/components/Campaign/CampaignProvider.tsx
- web/components/Campaign/Places/Application/Inputs/FileField.tsx
- web/public/assets/img/applicationDownload.svg
- web/public/assets/img/applicationSelected.svg
- web/public/locales/fr/application.json
- Ajout du drawer avec les infos de candidature
> Application drawer

- back/api/application/config/policies/can-update.js
- back/api/application/config/routes.json
- back/api/application/controllers/application.js
- back/extensions/documentation/documentation/1.0.0/full_documentation.json
- web/components/Account/Application/Place/ApplicationPlaceListItem.tsx
- web/components/Account/Application/Place/ApplicationPreselectButton.tsx
- web/components/Account/Application/Place/ApplicationStatusIcon.tsx
- web/components/Account/Application/Place/ApplicationsHelpers/ApplicationPlaceHelper.tsx
- web/components/Account/Application/Place/ApplicationsHelpers/ConfirmSelections.tsx
- web/components/Account/Application/Place/DetailDrawer/ApplicationRightPanel.tsx
- web/public/assets/icons/RemoveIcon.tsx
- web/public/locales/fr/application.json
- Présélection des candidatures
> Pre select applications

- back/extensions/documentation/documentation/1.0.0/full_documentation.json
- web/components/Account/Application/Place/ApplicationPlaceFetcher.tsx
- web/components/Account/Application/Place/ApplicationPlaceListItem.tsx
- web/components/Account/Application/Place/ApplicationStatusIcon.tsx
- web/components/Account/Application/Place/ApplicationsHelpers/ClosedCampaign.tsx
- web/components/Account/Application/Place/DetailDrawer/ApplicationPreselectButton.tsx
- web/components/Account/Application/Place/DetailDrawer/ApplicationRightPanel.tsx
- web/components/Account/Application/Place/DisponibilitiesSelector/DisponibilitiesSelector.tsx
- web/components/Account/Application/Place/DisponibilitiesSelector/DisponibilitiesSelectorFields.tsx
- web/public/locales/fr/application.json
- Display du listing des candidatures pour les campagnes fermées
> Closed campaign display

- web/components/Account/Place/Schedule.tsx
- web/components/Campaign/Places/Admin/CampaignDatePicker.tsx
- Améliorer le fonctionnement de l'exclusion des jours du calendrier
> Exclude days from calendar

- back/extensions/documentation/documentation/1.0.0/full_documentation.json
- web/components/Account/Place/PlaceTabList.tsx
> Fix space creation bug

- back/config/plugins.js
- back/extensions/documentation/documentation/1.0.0/full_documentation.json
- web/components/Account/Application/Company/ApplicationCompanyListItem.tsx
- web/components/Account/Application/Place/ApplicationDownloadAll.tsx
- web/components/Account/Application/Place/ApplicationPlaceData.tsx
- web/components/Account/Application/Place/ApplicationPlaceListItem.tsx
- web/components/Account/Application/Place/ApplicationsSearch.tsx
- web/components/Account/Application/Place/CampaignSelector/CampaignSelector.tsx
- web/components/Account/Application/Place/DisponibilitiesSelector/DisponibilitiesSelector.tsx
- web/components/Account/Application/Place/DisponibilitiesSelector/DisponibilitiesSelectorFields.tsx
https://github.com/premieroctet/studio-d-suivi/issues/6
> Listing candidatures fix 01/03

- back/extensions/documentation/documentation/1.0.0/full_documentation.json
- web/components/Campaign/Places/Application/CampaignApplicationScheduleItem.tsx
- web/components/Campaign/Places/Detail/CampaignDetailSwitcher.tsx
- web/components/Campaign/Places/Detail/CampaignDetailTabs.tsx
- web/components/Campaign/Places/Detail/CampaignPlaceDetail.tsx
- web/components/Home/HomePlacesCampaign.tsx
- web/components/Home/HomePlacesSolidarity.tsx
- web/components/Place/OtherPlaces.tsx
- web/components/Place/PlaceGridCard.tsx
- web/components/Place/PlaceHeader.tsx
- web/hooks/useCampaignDispo.tsx
- web/hooks/usePlaces.ts
- web/public/locales/fr/place.json
https://github.com/premieroctet/studio-d-suivi/issues/14
> Place campaign detail fixes 01/03

- web/components/Place/PlaceGridCard.tsx
https://github.com/premieroctet/studio-d-suivi/issues/23
> Fix places listing in campaign mode 01/03

- back/config/plugins.js
- web/components/Campaign/Places/Application/CampaignApplicationSchedule.tsx
- web/components/Campaign/Places/Application/CampaignApplicationScheduleItem.tsx
- web/components/Campaign/Places/Application/LockedApplications.tsx
- web/public/locales/fr/place.json
https://github.com/premieroctet/studio-d-suivi/issues/15
> Limit application number on schedule selection

- back/extensions/documentation/documentation/1.0.0/full_documentation.json
- web/components/FooterMenu.tsx
https://github.com/premieroctet/studio-d-suivi/issues/31
> Add extra link to footer nav

- back/extensions/documentation/documentation/1.0.0/full_documentation.json
- web/components/Account/Info/InfoCompanyApplications.tsx
https://github.com/premieroctet/studio-d-suivi/issues/12
> Fix link in no result page

- web/components/pdfs/ApplicationDocument.tsx
- web/components/pdfs/ApplicationHeader.tsx
- web/components/pdfs/ApplicationReference.tsx
- web/components/pdfs/ApplicationSection.tsx
- web/components/pdfs/DividerPage.tsx
- web/components/pdfs/pdfStyleUtils.ts
> Pdf font issue

- back/extensions/documentation/documentation/1.0.0/full_documentation.json
- web/components/Account/Application/Company/ApplicationCompanyList.tsx
- web/components/Account/Application/Company/ApplicationsHelpers/FullApplications.tsx
- web/components/Account/Application/Place/ApplicationDownloadAll.tsx
- web/components/Account/Application/Place/ApplicationPlaceList.tsx
- web/components/Campaign/Places/Application/LockedApplications.tsx
- web/components/Campaign/Places/Detail/CampaignPlaceDetail.tsx
- web/pages/api/pdfs/all/[id].tsx
- web/public/locales/fr/application.json
- web/public/locales/fr/place.json
- web/utils/pdf.ts
https://github.com/premieroctet/studio-d-suivi/issues/46
> Wording and style fixes

- web/components/Account/Application/Place/DetailDrawer/ApplicationDetailDrawer.tsx
- Responsive du drawer affichant le pdf de candidature
> Application detail drawer responsive

- web/components/Campaign/Places/Application/ApplicationRecap.tsx
- web/components/Campaign/Places/Application/CampaignApplicationPopin.tsx
- web/public/locales/fr/place.json
https://github.com/premieroctet/studio-d-suivi/issues/47
> Change button on campaign application summary

- back/extensions/documentation/documentation/1.0.0/full_documentation.json
- web/components/Account/AccountMenu.tsx
- web/components/Account/Application/Company/ApplicationCompanyList.tsx
- web/components/Account/Application/Place/ApplicationDownloadAll.tsx
- web/components/Account/Application/Place/DetailDrawer/ApplicationDetailDrawer.tsx
- web/components/Account/Application/Place/DetailDrawer/ApplicationDetails.tsx
- web/components/Account/Application/Place/DetailDrawer/ApplicationSection.tsx
- web/package.json
- web/pages/api/pdfs/all/[id].tsx
- web/pages/api/pdfs/selected/[id].tsx
- web/pages/compte/mes-candidatures/index.tsx
- web/public/locales/fr/place.json
- web/theme/index.ts
- web/utils/pdf.ts
- web/yarn.lock
-  [x] Il manque le feedback à l'annulation d'une candidature, le volet devrait se refermer. En l'état on reste sur le volet et si on re-clique sur annuler en pensant que l'action ne s'est pas effectuée, ça provoque une erreur.
> feat: various improvements

- web/components/Account/AccountMenu.tsx
- web/components/Account/Application/Place/ApplicationPlaceList.tsx
- web/components/Account/Application/Place/ApplicationPlaceListItem.tsx
- web/components/Account/Application/Place/DetailDrawer/ApplicationDetailDrawer.tsx
- web/components/pdfs/ApplicationHeader.tsx
- web/pages/api/pdfs/all/[id].tsx
- web/pages/api/pdfs/selected/[id].tsx
- web/pages/compte/mes-candidatures/index.tsx
- web/utils/pdf.ts
- Retour génération PDF
- Amélioration visionneuse PDF (natif)
- Masquage des campagnes si compagnie plus concernée
> feat: review

- web/components/Account/Application/Company/ApplicationsHelpers/ClosedApplications.tsx
- web/components/Campaign/Home/ApplicationsCampaignInsert.tsx
- web/components/Place/PlacesCampaignTabs.tsx
- web/public/locales/fr/account.json
- web/public/locales/fr/common.json
- web/public/locales/fr/place.json
Différents retours de Atelier de Paris
> wording reviewed

- back/api/application/controllers/application.js
- back/extensions/documentation/documentation/1.0.0/full_documentation.json
- web/components/Account/AccountMenu.tsx
- web/components/Campaign/CampaignProvider.tsx
- web/components/Campaign/Home/ApplicationsCampaignInsert.tsx
- web/components/Place/PlacesCampaignTabs.tsx
- web/pages/api/pdfs/selected/[id].tsx
- web/pages/compte/mes-candidatures/index.tsx
- changement structure dossier
- correction affichage lors des candidatures
> feat: folder improvement and bug fix

- web/components/Campaign/Places/Detail/CampaignDetailTabs.tsx
- web/components/Campaign/Places/Detail/CampaignPlaceDetail.tsx
- web/components/Place/PlacesPage.tsx
- Always display Solidarity tab
- Fix issue with `CampaignDetailSwitcher` visibility
- Temporary display 48 results on place pages
> fix: issues with campaign

- back/api/espace/controllers/espace.js
- web/components/Actuality/ActuCard.tsx
- web/components/Home/HomePlacesSolidarity.tsx
- web/components/Place/Booking/BookingRecapInsert/AuthBookingInsert.tsx
- web/components/Place/Booking/BookingRecapInsert/BookingRecap.tsx
- web/components/Place/PlaceDetailPage/PlaceDetailCalendar.tsx
- web/components/Place/PlaceGridCard.tsx
- web/components/Place/PlaceList.tsx
- web/components/Place/PlaceListCard.tsx
- web/components/Place/PlacesCampaignTabs.tsx
- web/components/Place/PlacesPage.tsx
- web/hooks/useDispoInRange.ts
- web/next.config.js
- web/pages/espaces/index.tsx
- https://github.com/AtelierdeParis/studio-d/issues/141
- https://github.com/AtelierdeParis/studio-d/issues/140
- https://github.com/AtelierdeParis/studio-d/issues/144
> Correction de l'affichage des dispos

- web/public/locales/fr/place.json
> Wording review

- back/api/application/config/routes.json
- back/api/application/controllers/application.js
- back/api/application/documentation/1.0.0/application.json
- back/api/application/documentation/1.0.0/overrides/application.json
- back/extensions/documentation/documentation/1.0.0/full_documentation.json
- web/next.config.js
- web/package.json
- web/pages/api/pdfs/selected/[id].tsx
- web/typings/api.ts
- web/yarn.lock
> feat: add pdf

- web/components/Navigation/Header.tsx
Trailing slash missing ending in error when link clocked from 'https://www.studiod-danse.fr/espaces/le-dancing' for example
> Fix issue with link in menu
